export enum NpiOrderFormField {
  PURCHASE_ORDER_NUMBER = "purchaseOrderNumber",
  WORK_ORDER_ID = "workOrderId",
  PART_NUMBER = "partNumber",
  QUANTITY = "quantity",
  ORDER_DATE = "orderDate",
  TARGET_DELIVERY_DATE = "targetDeliveryDate",
  CUSTOMER_NAME = "customerName",
  PRODUCT_NAME = "productName",
  MATERIAL_PURCHASE_PLAN_TIME_IN_HOURS = "materialPurchasePlanTimeInHours",
  MATERIAL_RECEIVING_PLAN_TIME_IN_HOURS = "materialReceivingPlanTimeInHours",
  PRODUCTION_PLAN_TIME_IN_HOURS = "productionPlanTimeInHours",
  TESTING_PLAN_TIME_IN_HOURS = "testingPlanTimeInHours",
  SHIPPING_PLAN_TIME_IN_HOURS = "shippingPlanTimeInHours",
  CUSTOMER_APPROVAL_PLAN_TIME_IN_HOURS = "customerApprovalPlanTimeInHours",
}
